cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('get-items/', views.get_cart_items, name='get_cart_items'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),  
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('about/', views.about, name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('search/', views.search_products, name='search_products'),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
# Defining URL patterns for the products app
urlpatterns = [
    path('', views.product_list, name='product_list'),  # List of products
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),  # Detail page for a product
    path('category/<slug:category_slug>/', views.category_products, name='category_products'),  # Products in category
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container m-5 mx-auto">
    <div class="row align-items-center " >
		<div class="col-md-6">
			<h1>Your <strong>Destination</strong> for Premium Papercraft Art</h1>
			<p>Welcome to <strong>Crafted Nature</strong>, where we transform paper into art with passion, precision, and unparalleled quality. Specializing in premium papercraft, we are dedicated to creating pieces that bring creativity and elegance into every detail.</p>

			<p>Founded on the belief that paper holds endless potential, our team of artisans and designers combines traditional techniques with innovative methods to craft stunning, high-quality works. From intricate designs to custom projects, each creation is made with the utmost care and dedication to excellence.</p>
		  
			<p>Whether you’re looking for custom décor, unique gifts, or elegant paper installations, <strong>Crafted Nature</strong> is here to bring your vision to life. Join us in exploring the endless possibilities of papercraft, and experience art like never before.</p>
		  
			<p>Thank you for choosing us to add a touch of handcrafted beauty to your world.</p>
		</div>
        <div class="col-md-6 overflow-hidden banner">
            <img src="{% static 'images/aboutus.webp' %}" class="img-fluid rounded-image" alt="art images">
        </div>
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<div class="container m-5 mx-auto">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Contact Us</h1>
      <p class="text-center mb-5">
        If you have any questions, feel free to reach out to us via the contact form below or at our email address.
      </p>

      {% if form.errors %}
        <div class="alert alert-danger">
          <ul>
            {% for field, errors in form.errors.items %}
              <li>{{ field.label }}: {{ errors|join:", " }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}

      <form method="post" action="{% url 'contact' %}">
        {% csrf_token %}
        
        <div class="form-group">
          {{ form.name.label_tag }}
          {{ form.name }}
        </div>

        <div class="form-group mt-3">
          {{ form.email.label_tag }}
          {{ form.email }}
        </div>

        <div class="form-group mt-3">
          {{ form.message.label_tag }}
          {{ form.message }}
        </div>

        <button type="submit" class="btn btn-warning btn-block mt-4 w-100">Send</button>
      </form>

    </div>
    <div class="col-md-6 d-none d-md-block">
      <img src="{% static 'images/contact.webp' %}" class="img-fluid rounded-image" alt="Contact image">
    </div>
  </div>
</div>
{% endblock %}

templates/contact_success.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card text-center shadow-sm">
                <div class="card-body">
                    <h1 class="card-title mb-4">Thank you for contacting us!</h1>
                    <p class="card-text">Your message has been sent successfully.</p>
                    <a href="/" class="btn btn-primary mt-3">Return to Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome to Crafted Nature{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-center" >
        <div class="col-md-6 overflow-hidden banner ">
            <img src="{% static 'images/banner.webp' %}" class="img-fluid rounded-image shadow" alt="banner">
        </div>
        <div class="col-md-6 mt-2 text-center text-md-start">
            <h1 class="main-text">Life’s <strong class="highlight">better</strong> when you live it with <strong>art</strong>.</h1>
            <p class="mb-4">Transform your space in one easy step with our premium paper craft.</p>
            <a href="{% url 'products:product_list' %}" class="btn btn-outline-warning border-3 text-decoration-none w-50 rounded-pill" style="color: black;"><strong>Shop our latest crafts</strong></a>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<h2>Register</h2>
<form method="POST" action="{% url 'register' %}">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Register</button>
</form>

{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% block content %}
<div class="container">
    
    <button class="btn btn-outline-secondary btn-light mt-4 mb-4"
    onclick="window.location.href='{% url 'products:product_list' %}'">Back to Products</button>

     <!-- Product Grid -->
     <div class="row">
        {% for product in products %}
        {% if category.name != "Uncategorized" %}
        <div class="col-md-4 mb-4 d-flex justify-content-center">
            <div class="card text-center border-bottom-0" style="width: 18rem;">
                <!-- Link na zdjęciu -->
                <a href="{% url 'products:product_detail' product.id %}">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top rounded-1" alt="{{ product.name }}"
                        style="border-radius: 0;">
                    {% else %}
                    <img src="https://via.placeholder.com/200" class="card-img-top" alt="Placeholder Image"
                        style="border-radius: 0;">
                    {% endif %}
                </a>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-muted flex-grow-1">{{ product.name }}</h5>
                    <p class="card-text text-muted text-center">{{ product.category }}</p>
                    <p class="card-text text-muted text-center">£{{ product.price }}</p><span>
                        <a href="#"
                            class="add-to-cart btn btn-warning w-100 py-1 mb-1 rounded-pill d-block text-center"
                            data-product-id="{{ product.id }}" data-stock="{{ product.stock }}">
                            <i class="fas fa-shopping-cart"></i> Add to Cart
                        </a></span>
                </div>
            </div>
            
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <button class="btn btn-outline-secondary btn-light mt-3"
    onclick="window.location.href='{% url 'products:product_list' %}'">Back to Products</button>
</div>
{% endblock %}